spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LaNguAx/bidpoint.git
          search-paths: config
          default-label: main